server:
  port: 8080
  servlet:
    context-path:

spring:
  application:
    name: ecommerce-order-system

  datasource:
    username: root
    password: root
    url: "jdbc:mysql://localhost:3306/ecommerce_db"

  jpa:
    hibernate:
      ddl-auto: update
